baseURL = "https://facundop.github.io/"
languageCode = "en-us"
title = "</ >"
theme = "ananke"
googleAnalytics = "UA-39473333-9"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10

enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Nice description."
  twitter = "https://twitter.com/facundopre"
  github = "https://github.com/facundop"
  linkedin = "https://www.linkedin.com/in/facundoprecentado/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2